name: default
fallback:
  fees:
    - flat_fee: 0.0
      percent_fee: 0.0
  slippage:
    market_bps: 5.0
    use_bar_range: false
bundles:
  alpaca:crypto:
    fees:
      - flat_fee: 0.0
        percent_fee: 0.0025
    slippage:
      market_bps: 15.0
      use_bar_range: true
  alpaca:equity:
    fees:
      - flat_fee: 0.0
        percent_fee: 0.0
    slippage:
      market_bps: 2.0
      use_bar_range: false
  tradier:options:
    fees:
      - flat_fee: 0.67
        percent_fee: 0.0
    slippage:
      market_bps: 50.0
      use_bar_range: false
