"""initial schema

Revision ID: 392143345ff0
Revises: 
Create Date: 2026-05-12 17:03:38.764190
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '392143345ff0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('broker_type', sa.String(), nullable=False),
    sa.Column('credentials', sa.Text(), nullable=False),
    sa.Column('supported_asset_types', sa.JSON(), nullable=False),
    sa.Column('options_level', sa.Integer(), nullable=True),
    sa.Column('account_features', sa.JSON(), nullable=True),
    sa.Column('pdt_mode', sa.String(), nullable=False),
    sa.Column('locked_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['locked_by'], ['algorithm_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('algorithm_instances',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('algorithm_id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('worker_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('active_run_id', sa.String(), nullable=True),
    sa.Column('config_values', sa.JSON(), nullable=True),
    sa.Column('persisted_state', sa.JSON(), nullable=True),
    sa.Column('state_stale', sa.Boolean(), nullable=False),
    sa.Column('lifetime_metrics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['active_run_id'], ['algorithm_runs.id'], ),
    sa.ForeignKeyConstraint(['algorithm_id'], ['algorithms.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('algorithm_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('instance_id', sa.String(), nullable=False),
    sa.Column('run_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('starting_equity', sa.Float(), nullable=True),
    sa.Column('ending_equity', sa.Float(), nullable=True),
    sa.Column('net_pnl', sa.Float(), nullable=True),
    sa.Column('unrealized_pnl', sa.Float(), nullable=True),
    sa.Column('total_fees', sa.Float(), nullable=False),
    sa.Column('total_slippage', sa.Float(), nullable=False),
    sa.Column('trade_count', sa.Integer(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('equity_curve', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['algorithm_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('algorithms',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('repo_url', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('commit_hash', sa.String(), nullable=True),
    sa.Column('required_asset_types', sa.JSON(), nullable=True),
    sa.Column('required_options_level', sa.Integer(), nullable=True),
    sa.Column('required_account_features', sa.JSON(), nullable=True),
    sa.Column('supported_brokers', sa.JSON(), nullable=True),
    sa.Column('data_dependencies', sa.JSON(), nullable=True),
    sa.Column('config_schema', sa.JSON(), nullable=True),
    sa.Column('custom_events', sa.JSON(), nullable=True),
    sa.Column('install_status', sa.String(), nullable=False),
    sa.Column('install_error', sa.Text(), nullable=True),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_archival',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('date_range_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_range_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_sources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('routed_to_discord', sa.Boolean(), nullable=False),
    sa.Column('discord_channel', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_data_downloads',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('symbols', sa.JSON(), nullable=False),
    sa.Column('date_range_start', sa.Date(), nullable=False),
    sa.Column('date_range_end', sa.Date(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('data_type', sa.String(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('progress_current', sa.Integer(), nullable=False),
    sa.Column('progress_total', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scrapers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('repo_url', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('commit_hash', sa.String(), nullable=True),
    sa.Column('schedule', sa.String(), nullable=True),
    sa.Column('output_format', sa.String(), nullable=True),
    sa.Column('output_filename', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('dependent_algorithm_count', sa.Integer(), nullable=False),
    sa.Column('last_success', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('encrypted', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('workers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tailscale_ip', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_algorithms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account_cash_flows',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_value', sa.Float(), nullable=False),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.Column('positions_value', sa.Float(), nullable=False),
    sa.Column('net_deposits_cumulative', sa.Float(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('backtest_comparisons',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('instance_id', sa.String(), nullable=False),
    sa.Column('algorithm_id', sa.String(), nullable=False),
    sa.Column('time_range_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_range_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_ticks', sa.Integer(), nullable=False),
    sa.Column('matching_ticks', sa.Integer(), nullable=False),
    sa.Column('match_percentage', sa.Float(), nullable=False),
    sa.Column('divergences', sa.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['algorithm_id'], ['algorithms.id'], ),
    sa.ForeignKeyConstraint(['instance_id'], ['algorithm_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decision_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('instance_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('tick_data', sa.JSON(), nullable=True),
    sa.Column('signals_produced', sa.JSON(), nullable=True),
    sa.Column('reasoning', sa.JSON(), nullable=True),
    sa.Column('data_sources_used', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['algorithm_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_decision_log_instance_mode_ts', 'decision_log', ['instance_id', 'mode', 'timestamp'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('instance_id', sa.String(), nullable=True),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('strategy_type', sa.String(), nullable=False),
    sa.Column('legs', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('open_group_id', sa.String(), nullable=True),
    sa.Column('close_group_id', sa.String(), nullable=True),
    sa.Column('net_cost', sa.Float(), nullable=False),
    sa.Column('net_proceeds', sa.Float(), nullable=True),
    sa.Column('net_pnl', sa.Float(), nullable=True),
    sa.Column('unrealized_pnl', sa.Float(), nullable=True),
    sa.Column('total_fees', sa.Float(), nullable=False),
    sa.Column('adjustments', sa.JSON(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['instance_id'], ['algorithm_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('instance_id', sa.String(), nullable=True),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('position_id', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('order_type', sa.String(), nullable=False),
    sa.Column('requested_price', sa.Float(), nullable=True),
    sa.Column('filled_price', sa.Float(), nullable=False),
    sa.Column('fees', sa.Float(), nullable=False),
    sa.Column('fee_breakdown', sa.JSON(), nullable=True),
    sa.Column('slippage', sa.Float(), nullable=True),
    sa.Column('is_day_trade', sa.Boolean(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['instance_id'], ['algorithm_instances.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pdt_tracking',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('trade_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('open_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('close_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('day_trade_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['trade_id'], ['trade_log.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pdt_tracking')
    op.drop_table('trade_log')
    op.drop_table('positions')
    op.drop_index('ix_decision_log_instance_mode_ts', table_name='decision_log')
    op.drop_table('decision_log')
    op.drop_table('backtest_comparisons')
    op.drop_table('account_snapshots')
    op.drop_table('account_cash_flows')
    op.drop_table('workers')
    op.drop_table('settings')
    op.drop_table('scrapers')
    op.drop_table('market_data_downloads')
    op.drop_table('events')
    op.drop_table('data_sources')
    op.drop_table('data_archival')
    op.drop_table('algorithms')
    op.drop_table('algorithm_runs')
    op.drop_table('algorithm_instances')
    op.drop_table('accounts')
    # ### end Alembic commands ###
