"""parameter_sets

Revision ID: 3fd58eade4c4
Revises: fafe5be0caa5
Create Date: 2026-05-19 16:32:40.294886
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3fd58eade4c4'
down_revision: Union[str, None] = 'fafe5be0caa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parameter_sets',
    sa.Column('id', sa.String(length=6), nullable=False),
    sa.Column('algorithm_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('config_values', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['algorithm_id'], ['algorithms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('algorithm_id', 'id')
    )
    with op.batch_alter_table('algorithm_instances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parameter_set_id', sa.String(length=6), nullable=True))

    with op.batch_alter_table('backtest_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parameter_set_id', sa.String(length=6), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backtest_runs', schema=None) as batch_op:
        batch_op.drop_column('parameter_set_id')

    with op.batch_alter_table('algorithm_instances', schema=None) as batch_op:
        batch_op.drop_column('parameter_set_id')

    op.drop_table('parameter_sets')
    # ### end Alembic commands ###
