"""add algorithm source_path

Revision ID: 64b8f4780606
Revises: 85bc13f9b381
Create Date: 2026-05-17 11:33:18.048224
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '64b8f4780606'
down_revision: Union[str, None] = '85bc13f9b381'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('algorithms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_path', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('algorithms', schema=None) as batch_op:
        batch_op.drop_column('source_path')

    # ### end Alembic commands ###
