"""add worker_activity

Revision ID: 71e20fc1d3ee
Revises: ae2dd86e1330
Create Date: 2026-05-16 10:33:02.924893
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '71e20fc1d3ee'
down_revision: Union[str, None] = 'ae2dd86e1330'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_activity',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('worker_id', sa.String(), nullable=False),
    sa.Column('instance_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('logger_name', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['algorithm_instances.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('worker_activity', schema=None) as batch_op:
        batch_op.create_index('ix_worker_activity_instance_ts', ['instance_id', 'timestamp'], unique=False)
        batch_op.create_index('ix_worker_activity_worker_ts', ['worker_id', 'timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker_activity', schema=None) as batch_op:
        batch_op.drop_index('ix_worker_activity_worker_ts')
        batch_op.drop_index('ix_worker_activity_instance_ts')

    op.drop_table('worker_activity')
    # ### end Alembic commands ###
