"""add algorithm_deployment_reports

Revision ID: 85bc13f9b381
Revises: 71e20fc1d3ee
Create Date: 2026-05-16 10:52:00.651744
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '85bc13f9b381'
down_revision: Union[str, None] = '71e20fc1d3ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('algorithm_deployment_reports',
    sa.Column('deployment_id', sa.String(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_return', sa.Float(), nullable=True),
    sa.Column('cagr', sa.Float(), nullable=True),
    sa.Column('volatility', sa.Float(), nullable=True),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('sortino_ratio', sa.Float(), nullable=True),
    sa.Column('calmar_ratio', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('max_drawdown_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('romad', sa.Float(), nullable=True),
    sa.Column('total_fees_paid', sa.Float(), nullable=True),
    sa.Column('total_slippage_dollars', sa.Float(), nullable=True),
    sa.Column('trade_count', sa.Integer(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('profit_factor', sa.Float(), nullable=True),
    sa.Column('avg_win', sa.Float(), nullable=True),
    sa.Column('avg_loss', sa.Float(), nullable=True),
    sa.Column('expectancy', sa.Float(), nullable=True),
    sa.Column('longest_drawdown_days', sa.Integer(), nullable=True),
    sa.Column('longest_winning_streak', sa.Integer(), nullable=True),
    sa.Column('longest_losing_streak', sa.Integer(), nullable=True),
    sa.Column('equity_curve', sa.JSON(), nullable=True),
    sa.Column('drawdown_curve', sa.JSON(), nullable=True),
    sa.Column('drawdown_periods', sa.JSON(), nullable=True),
    sa.Column('key_metrics', sa.JSON(), nullable=True),
    sa.Column('rolling_metrics', sa.JSON(), nullable=True),
    sa.Column('monthly_returns_matrix', sa.JSON(), nullable=True),
    sa.Column('eoy_returns', sa.JSON(), nullable=True),
    sa.Column('runs_index', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['deployment_id'], ['algorithm_instances.id'], ),
    sa.PrimaryKeyConstraint('deployment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('algorithm_deployment_reports')
    # ### end Alembic commands ###
