"""live_subs and worker_tailscale_ip_nullable

Revision ID: 89c7f5ff5cd9
Revises: c3d4e5f6a7b8
Create Date: 2026-05-14 15:19:11.265895
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '89c7f5ff5cd9'
down_revision: Union[str, None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers') as batch_op:
        batch_op.alter_column('tailscale_ip',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers') as batch_op:
        batch_op.alter_column('tailscale_ip',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
