"""backtest_runs

Revision ID: 95f4bf13d375
Revises: 89c7f5ff5cd9
Create Date: 2026-05-14 19:15:07.612243
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '95f4bf13d375'
down_revision: Union[str, None] = '89c7f5ff5cd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('algorithm_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('date_range_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_range_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('initial_cash', sa.Float(), nullable=False),
    sa.Column('config_overrides', sa.JSON(), nullable=True),
    sa.Column('buy_trading_fees', sa.JSON(), nullable=True),
    sa.Column('sell_trading_fees', sa.JSON(), nullable=True),
    sa.Column('slippage_model', sa.JSON(), nullable=True),
    sa.Column('benchmark_symbol', sa.String(), nullable=True),
    sa.Column('benchmark_source', sa.String(), nullable=True),
    sa.Column('progress_message', sa.Text(), nullable=True),
    sa.Column('progress_pct', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('total_return', sa.Float(), nullable=True),
    sa.Column('cagr', sa.Float(), nullable=True),
    sa.Column('volatility', sa.Float(), nullable=True),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('sortino_ratio', sa.Float(), nullable=True),
    sa.Column('calmar_ratio', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('max_drawdown_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('romad', sa.Float(), nullable=True),
    sa.Column('total_fees_paid', sa.Float(), nullable=True),
    sa.Column('total_slippage_dollars', sa.Float(), nullable=True),
    sa.Column('trade_count', sa.Integer(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('profit_factor', sa.Float(), nullable=True),
    sa.Column('avg_win', sa.Float(), nullable=True),
    sa.Column('avg_loss', sa.Float(), nullable=True),
    sa.Column('expectancy', sa.Float(), nullable=True),
    sa.Column('longest_drawdown_days', sa.Integer(), nullable=True),
    sa.Column('longest_winning_streak', sa.Integer(), nullable=True),
    sa.Column('longest_losing_streak', sa.Integer(), nullable=True),
    sa.Column('equity_curve', sa.JSON(), nullable=True),
    sa.Column('trades', sa.JSON(), nullable=True),
    sa.Column('drawdown_periods', sa.JSON(), nullable=True),
    sa.Column('tearsheet_path', sa.String(), nullable=True),
    sa.Column('download_ids', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['algorithm_id'], ['algorithms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('market_data_downloads', schema=None) as batch_op:
        batch_op.alter_column('current_symbol_pct',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_data_downloads', schema=None) as batch_op:
        batch_op.alter_column('current_symbol_pct',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)

    op.drop_table('backtest_runs')
    # ### end Alembic commands ###
