"""worker version column

Revision ID: fafe5be0caa5
Revises: b53bce348238
Create Date: 2026-05-19 13:29:49.337009
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fafe5be0caa5'
down_revision: Union[str, None] = 'b53bce348238'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.drop_column('version')

    # ### end Alembic commands ###
