"""account can_trade

Revision ID: feec91c15462
Revises: cd3bba59b349
Create Date: 2026-05-18 16:54:52.380741
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'feec91c15462'
down_revision: Union[str, None] = 'cd3bba59b349'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_trade', sa.Boolean(), nullable=False, server_default=sa.true()))

    with op.batch_alter_table('market_data_downloads', schema=None) as batch_op:
        batch_op.alter_column('current_symbol_pct',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_data_downloads', schema=None) as batch_op:
        batch_op.alter_column('current_symbol_pct',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('can_trade')

    # ### end Alembic commands ###
